### ISSUE TITLE
Getting unexpected hub addresses on macOS 12.4 (21F79) and later

### ISSUE THREAD

**Issue by dyhopper** [mvp/uhubctl#419] opened 2022-05-24 22:19 UTC
We have a testing setup where we daisy-chain 2 smart hubs and have sensors plugged into the child hub that we turn on/off with this excellent tool.
This has always given us addresses like 20-3.1.1 (for port 1 on child hub when this hub was plugged into port 1 of parent). However with macOS 12.5 Beta using the same machine and hub setup, we only get hub addresses with 2 levels. For example we get 20-3, 20-4, 0-3, 0-4, 20-3, and 0-1 with our current setup.  Note that 20-3 is listed twice. 

Again, this is macOS BETA, so it's possible it will be "fixed" when macOS comes out of beta. Also, I can likely work around this if needed. But I thought I'd bring it up in case uhubctl might need some updates for macOS 12.5.

**Comment by mvp** [comment] 2022-05-25 00:11
Thanks for heads up!
We had similar breakage for MacOS 10.5 https://github.com/libusb/libusb/issues/707.
This is not `uhubctl` problem, but `libusb` problem - `uhubctl` relies on `libusb_get_port_numbers` working correctly.
Back then it was fixed by changing Mac specific `libusb` code in https://github.com/libusb/libusb/pull/712.
I expect that we will have to do something similar if it is not fixed in beta.

**Comment by mvp** [comment] 2022-06-18 00:48
Lets close this for now. May need to re-open when MacOS 12.5 is released and if this issue is present in it.

**Comment by MPLew-is** [comment] 2022-06-18 02:54
This exact issue is also occurring for me on 12.4, can this be reopened?

**Comment by mvp** [comment] 2022-06-18 06:27
@MPLew-is, can you please give more info about your hardware: Mac model, OS version, libusb version, uhubctl version, how did you build/install both libusb and uhubctl? If you have libusb older than current 1.0.26 and uhubctl older than 2.4.0, please try installing latest versions first from homebrew. Thanks!

**Comment by MPLew-is** [comment] 2022-06-20 04:31
![Screen Shot 2022-06-19 at 22 26 41](https://user-images.githubusercontent.com/11891085/174525579-99bb14b9-7a7e-405e-97f9-3ebe4a671a4b.png)
![Screen Shot 2022-06-19 at 22 27 31](https://user-images.githubusercontent.com/11891085/174525589-a9856d9f-e493-48b0-94d2-a1d5f18eb44f.png)

Already fully up to date, with both `libusb` and `uhubctl` installed via Homebrew.

**Comment by mvp** [comment] 2022-06-20 16:56
I can also reproduce it on MacOS 12.4 (21F79).
This is some OS change that broke libusb `libusb_get_port_numbers()`.
Easiest way to reproduce is to build libusb and run `examples/listdevs` - it should list device path with dots present.
I will dig a bit more into this and file a bug against libusb.

**Comment by mvp** [comment] 2022-06-20 18:40
Filed this issue with libusb https://github.com/libusb/libusb/issues/1156

**Comment by mcuee** [comment] 2022-06-26 10:23
Strange that for my Mac Mini M1 running macOS 12.4, both libusb listdev and uhubctl seem to work fine.
* https://github.com/libusb/libusb/issues/1156#issuecomment-1166474660

**Comment by MPLew-is** [comment] 2022-07-20 22:12
This seems to be fixed on macOS 12.5 that dropped today:

![Untitled](https://user-images.githubusercontent.com/11891085/180091406-6009dfb9-dad5-4b88-b9fe-db9bd2732922.png)

**Closed** 2022-07-20 23:49 UTC

**Comment by mvp** [comment] 2022-07-20 23:50
Issue closed, workaround is to upgrade to MacOS 12.5. Noted in README too.
