### ISSUE TITLE
Device descriptor is missing on MacOS 12.4(21F79)

### ISSUE THREAD

**Issue by kuudoz** [mvp/uhubctl#424] opened 2022-06-20 19:34 UTC
We have a test setup for managing our devices by toggling them on/off with this tool.
Unfortunately since the OS update  MacOS12.4, our device descriptors are now missing.
MacOS12.4
![12 4 uhubctl](https://user-images.githubusercontent.com/24995316/174667109-19b9139d-3a52-4a9a-a1eb-420e739b1a66.png)

on a different device using MacOS 10.15.7(19H524)
![10 5](https://user-images.githubusercontent.com/24995316/174667803-8d455827-4249-4420-b7b6-64c891773986.png)

As we can see descriptors are missing and both devices are using the same hub.
I noticed in the open issue #419 there was a similar issue from which the cause is libusb. Im suspecting the issue might be from libusb_get_device_descriptor not working correctly since the update.
Thanks!

**Comment by mvp** [comment] 2022-06-20 19:43
This is duplicate of issue #419 - real bug is https://github.com/libusb/libusb/issues/1156.
I have added a warning into README.md that libusb (and uhubctl) is broken on MacOS 12.4 (21F79) due to MacOS changed USB stack behavior.

**Closed by mvp** 2022-06-20 19:43 UTC
Labels: duplicate
